### ISSUE TITLE
Js files are missing from distributed version

### ISSUE THREAD

**Issue by stephanebachelier** [sindresorhus/pkg-versions#1]
There are in the Github release but not when installing from `npm`. 

```bash
❯ ls node_modules/pkg-versions
license      package.json readme.md
```

**Comment by SamVerschueren** [comment]
Good catch. It was due to [an issue with npm publish](https://github.com/SamVerschueren/npm-publish-index-test) that got resolved in the mean time. We only need to publish this one again.

**Comment by sindresorhus** [comment]
Done
